version: "3.3"
services:
  api:
    container_name: charllenger-Api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    command: bash -c 'yarn dev'
    logging:
      driver: none
