version: "3.3"
services:
  api:
    container_name: charllenger-Api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3001
    ports:
      - 3001:3001
    command: bash -c 'yarn dev'
